# Generated by Django 2.1.5 on 2019-02-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=30, unique=True, verbose_name='文件名')),
                ('createDate', models.DateField(unique=True, verbose_name='创建日期')),
                ('filePayload', models.FileField(upload_to='documents/upload/', verbose_name='文件负载')),
                ('uploader', models.CharField(max_length=30, unique=True, verbose_name='上传者')),
            ],
        ),
    ]
